# Use a imagem base do NGINX
FROM nginx:latest

# Copie o arquivo HTML para o diretório padrão de conteúdo do NGINX
COPY index.html /usr/share/nginx/html/

# Exponha a porta padrão do NGINX
EXPOSE 80
