# Use a imagem base do Python
FROM python:3.9-alpine

# Copie o script Python para o contêiner
COPY app.py /app.py

# Defina o comando para executar o script automaticamente quando o contêiner iniciar
CMD ["python", "/app.py"]
