# docker-compose.yml
version: '3'

services:
  redis:
    image: redis:latest
    container_name: meu-redis
    ports:
      - "6379:6379"

  web:
    build: ./app
    container_name: meu-app-web
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
